### ISSUE TITLE
As a developer, I need to research and familiarize myself with MERN so that I can contribute to making this a robust product.

### ISSUE THREAD

**Issue by Kshoes** [nyu-software-engineering/oink#22]

**Comment by sesphelan** [comment]
# Estimation of Work
L

# Acceptance Criteria
-[ ] Complete Lynda tutorials (or other tutorial of similar detail)
-[ ] Set up MERN environment for project
-[ ] Ensure environment runs on all member's computers
-[ ] Design Mongoose schemas

**Comment by jojox25** [comment]
## Estimation of Work 
L

## Acceptance criteria  
- [ ] Look through the resources that Prof posted in Slack to familiarize yourself with MERN
- [ ] **[NPM](https://www.lynda.com/Node-js-tutorials/Learning-npm-Node-Package-Manager-2018/761956-2.html)** (used to install Node.js, React, and many other projects)
- [ ] **[Node.js and Express.js](https://www.lynda.com/Node-js-tutorials/Building-RESTful-Web-APIs-Node-js-Express/633869-2.html)** (for the back-end of a web app) 
- [ ] **[React.js](https://www.lynda.com/React-js-tutorials/Learning-React-js/645064-2.html)** (for the front-end of a web app)
