### ISSUE TITLE
As a developer, I need to create Planning Poker cards or obtain an agreed-upon deck of Planning Poker cards, so that the team may estimate work effectively for the duration of the project.

### ISSUE THREAD

**Issue by Kshoes** [nyu-software-engineering/oink#24]

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2019-oink - nice work on the issues.  You will want to add the relevant issues to the Sprint 0 task board.  

Any user story in the task board must also contain the Acceptance Criteria and Estimate of Work, and must be broken up into individual tasks (as separate Issues) necessary to complete them.  Issues not in the current sprint don't need these.
